---
title: "Shortbred results"
author: "Fiona Tamburini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: paper
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

## CARD database
```{r}
library(cowplot)
library(DT)
library(genefilter)
library(ggpubr)
library(harrietr)
library(here)
library(tidyverse)

# read metadata ---
za_meta <- readRDS(here("rds/za_meta.rds"))
za_pheno <- readRDS(here("rds/za_pheno.rds"))
za_pheno$site_abbrev <- ifelse(za_pheno$site == "Bushbuckridge", "BBR", "SWT")

# read shortbred data ---
card <- read.table(here("input_final/shortbred/CARD_merge.txt"), sep = "\t", header = T)
vf <- read.table(here("input_final/shortbred/VF_merge_filtered.txt"), sep = "\t", header = T)

card_wide <- card %>%
  filter(Sample %in% za_meta$sample, Count > 0, Hits > 0) %>%
  pivot_wider(id_cols = c(Family, TotMarkerLength), names_from = Sample, values_from = Count, values_fill = 0) %>%
  separate(col = Family, into = c("db", "accession", "aro", "name"), sep = "\\|", remove = F)

vf_wide <- vf %>%
  filter(Sample %in% za_meta$sample) %>%
  pivot_wider(id_cols = c(Family, TotMarkerLength), names_from = Sample, values_from = Count, values_fill = 0)

# read card metadata ----
aro_desc <- read.csv(here("input_final/shortbred/aro.csv"))
aro_desc$Accession <- gsub(":", "_", aro_desc$Accession)

# read vfdb metadata ----
vfdb_meta <- read.table(here("input_final/shortbred/vfdb_meta.txt"),
                        sep = "\t", quote = "", col.names = c("Family", "gene", "description"))
victors_meta <- read.table(here("input_final/shortbred/victors_meta.txt"),
                           sep = "\t", comment.char = "", quote = "")
victors_meta <- victors_meta %>%
  mutate(Family = paste(V1, V2, V3, V4, sep = "|")) %>%
  dplyr::select(Family, V5)
names(victors_meta) <- c("Family", "description")

# card wilcoxon test by site ----
card_long <- reshape2::melt(card_wide,
                            id.vars = c("Family", "db", "accession", "aro", "name", "TotMarkerLength"),
                            variable.name = "sample", value.name = "rpkm")

card_long <- merge(card_long, za_pheno, all.x = T, all.y = F, by = "sample")  

wilcox_res <- card_long %>%
  group_by(Family, aro, name) %>%
  summarize(pvalue = wilcox.test(rpkm ~ site)$p.value,
            mean_swt = mean(rpkm[site == "Soweto"]),
            mean_bbr = mean(rpkm[site == "Bushbuckridge"])) %>%
  ungroup() %>%
  mutate(padj = p.adjust(pvalue, method = "fdr"),
         aro_name = aro_desc[match(aro, aro_desc$Accession), "Name"],
         inc_bbr = mean_bbr > mean_swt)

# obese vs lean
wilcox_res_bmi <- card_long %>%
  filter(bmi_status != "Overweight") %>%
  group_by(Family, aro, name) %>%
  summarize(pvalue = wilcox.test(rpkm ~ bmi_status)$p.value,
            mean_obese = mean(rpkm[bmi_status == "Obese"]),
            mean_lean = mean(rpkm[bmi_status == "Lean"])) %>%
  ungroup() %>%
  mutate(padj = p.adjust(pvalue, method = "fdr"),
         aro_name = aro_desc[match(aro, aro_desc$Accession), "Name"],
         inc_obese = mean_obese > mean_lean)
```

### Significant features by site (5% FDR)
```{r}
fdr_cutoff <- 0.05
res_signif <- wilcox_res %>%
  filter(padj < fdr_cutoff) %>%
  arrange(inc_bbr, padj) %>%
  dplyr::select(-Family)

datatable(res_signif %>%
            mutate(across(where(is.numeric), ~ signif(., 3))))

fdr_cutoff <- 0.01
res_top <- wilcox_res %>%
  filter(padj < fdr_cutoff) %>%
  arrange(inc_bbr, padj)

card_plot <- card_long %>%
  filter(Family %in% res_top$Family) %>%
  mutate(label = paste(aro, name, sep = "\n"))

# pseudo count
card_plot$rpkm[card_plot$rpkm == 0] <- 0.01
```

### Top features (1% FDR)
```{r, fig.width = 8, fig.height = 10}
ggplot(card_plot, aes(site_abbrev, rpkm, color = site)) +
  geom_jitter(width = 0.3, alpha = 0.75) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  facet_wrap(~label, scales = "free_y") +
  scale_y_log10() +
  theme_cowplot() +
  theme(axis.text.y = element_text(size = 10),
        strip.text = element_text(size = 11),
        legend.position = "none") +
  background_grid() +
  labs(x = "")
```

```{r}
datatable(aro_desc, filter = "top")
```

### Features associated with BMI: obese versus lean (5% FDR)
```{r}
fdr_cutoff <- 0.05
res_signif <- wilcox_res_bmi %>%
  filter(padj < fdr_cutoff) %>%
  arrange(inc_obese, padj) %>%
  dplyr::select(-Family)

datatable(res_signif %>%
            mutate(across(where(is.numeric), ~ signif(., 3))))

fdr_cutoff <- 0.01
res_top <- wilcox_res_bmi %>%
  filter(padj < fdr_cutoff) %>%
  arrange(inc_obese, padj)

card_plot <- card_long %>%
  filter(Family %in% res_top$Family) %>%
  mutate(label = paste(aro, name, sep = "\n"))

# pseudo count
card_plot$rpkm[card_plot$rpkm == 0] <- 0.01
```

```{r}
datatable(res_signif)
```

# To do: partial spearman correcting for site, age
```{r}
card_wide_t <- card_wide %>%
  column_to_rownames("Family") %>%
  select(-c(db, accession, aro, name, TotMarkerLength)) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  left_join(za_pheno[, c("sample", "bmi")], by = "sample") %>%
  column_to_rownames("sample") %>%
  filter(!is.na(bmi))

# spearman cor
sp_cor <- cor(card_wide_t, method = "spearman")
sp_cor_long <- melt_dist(sp_cor)

sp_cor_long %>%
  filter(iso1 == "bmi") %>%
  arrange(-abs(dist)) %>%
  head()

# partial spearman
pp_cor <- ppcor::pcor(card_wide_t, method = "spearman")
pp_cor <- data.frame(pp_cor$estimate)
names(pp_cor) <- names(card_wide_t)
rownames(pp_cor) <- names(card_wide_t)
pp_cor_long <- melt_dist(pp_cor)

pp_cor_long %>%
  filter(iso1 == "bmi") %>%
  arrange(-abs(dist)) %>%
  head()

# ggplot(card_wide_t, aes(bmi, `gb|NP_414995_1|ARO_3000216|acrB`)) +
#   geom_point()
```

## Virulence factors

Features from VFDB, Mvirdb, Victors

```{r, fig.width = 8, fig.height = 7}
### VF by site ----
# remove mvirdb - no metadata
vf_wide_filt <- vf_wide %>%
  filter(!grepl("^virulence\\|", Family))

vf_wide_filt <- vf_wide_filt[genefilter(vf_wide_filt[, 3:ncol(vf_wide_filt)], pOverA(0.2, 0)), ]

vf_long <- reshape2::melt(vf_wide_filt,
                            id.vars = c("Family", "TotMarkerLength"),
                            variable.name = "sample", value.name = "rpkm")

vf_long <- merge(vf_long, za_pheno, all.x = T, all.y = F, by = "sample")  

wilcox_res <- vf_long %>%
  group_by(Family) %>%
  summarize(pvalue = wilcox.test(rpkm ~ site)$p.value,
            mean_swt = mean(rpkm[site == "Soweto"]),
            mean_bbr = mean(rpkm[site == "Bushbuckridge"])) %>%
  ungroup() %>%
  mutate(padj = p.adjust(pvalue, method = "fdr"))

fdr_cutoff <- 0.01
res_top <- wilcox_res %>%
  filter(padj < fdr_cutoff) %>%
  mutate(inc_bbr = mean_bbr > mean_swt) %>%
  arrange(inc_bbr, padj)

n <- 20
vf_plot <- vf_long %>%
  filter(Family %in% res_top$Family[1:n]) %>%
  mutate(label = as.numeric(as.factor(Family)))

# pseudo count
vf_plot$rpkm[vf_plot$rpkm == 0] <- 0.01

ggplot(vf_plot, aes(site_abbrev, rpkm, color = site)) +
  geom_jitter(width = 0.3, alpha = 0.75) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  facet_wrap(~label, scales = "free_y") +
  scale_y_log10() +
  theme_cowplot() +
  theme(axis.text.y = element_text(size = 10),
        strip.text = element_text(size = 11),
        legend.position = "none") +
  background_grid() +
  labs(x = "")
```

```{r}
meta_both <- rbind(vfdb_meta[, -2], victors_meta)
meta_both$Family <- gsub(":", "_", meta_both$Family)

vf_desc <- vf_plot %>%
  dplyr::select(label, Family) %>%
  distinct() %>%
  mutate(db = gsub("\\|.+", "", Family),
         Family = gsub("VFDB\\||Victors\\||\\|$", "", Family), # format for matching to meta
         Family = gsub("_([0-9]$)", "\\.\\1", Family), # format to match meta
         Family = gsub("_gi", " gi", Family), # format to handle multiple gi ids in one entry
         description = meta_both[match(Family, meta_both$Family), "description"]) %>%
  arrange(label)

datatable(vf_desc, rownames = F)
```

### Features associated with BMI
```{r}
vf_wide_t <- vf_wide %>%
  column_to_rownames("Family") %>%
  select(-TotMarkerLength) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  left_join(za_pheno[, c("sample", "bmi")], by = "sample") %>%
  column_to_rownames("sample") %>%
  filter(!is.na(bmi))

# spearman cor
sp_cor <- cor(vf_wide_t, method = "spearman")
sp_cor_long <- melt_dist(sp_cor)

sp_cor_long %>%
  filter(iso1 == "bmi") %>%
  arrange(-abs(dist)) %>%
  head()

# partial spearman
pp_cor <- ppcor::pcor(vf_wide_t, method = "spearman")
pp_cor <- data.frame(pp_cor$estimate)
names(pp_cor) <- names(vf_wide_t)
rownames(pp_cor) <- names(vf_wide_t)
pp_cor_long <- melt_dist(pp_cor)

pp_cor_long %>%
  filter(iso1 == "bmi") %>%
  arrange(-abs(dist)) %>%
  head()
```